### ISSUE TITLE
Missing logs, favorite and timers and modification buttons

### ISSUE THREAD

**Issue by jfalmeida** [domoticz/Machinon#132]
Hey,

I did a clean install on my domoticz and I'm now missing these buttons.
![image](https://github.com/domoticz/Machinon/assets/2064092/c7cc7895-b9c0-40e6-b5c2-0fe7fd5653d3)
I've inspected the code and there is a property called display under .options that is set to "none"; if i disable it, the text appears (but no icons). 

Thanks

**Comment by mkampstra** [comment]
Discovered this also. Why is there no response after 2 wks? It is in beta and stable.

**Comment by jfalmeida** [comment]
After 6 years, I've moved on from domoticz to home assistant; It has a much stronger and active comunity (although I not a big fan of YAML)

**Comment by MadPatrick** [comment]
I'm having the same issue
It appeared when i upgrade my Domoticz.

**Comment by Argenlos** [comment]
Hello, Same problem.

**Comment by MadPatrick** [comment]
> Still an issue?

Yes.  This is still an issue

**Comment by DewGew** [comment]
Strange I dont have this issue, Im rinning latest beta of domoticz

**Comment by MadPatrick** [comment]
Not sure after which beta it appeared, anymore, but it is still with stable 2023.2
I've tried it even with a clean install of Domoticz and Machinon.

**Comment by DewGew** [comment]
same as #135

**Comment by rnollen** [comment]
Not sure if I have the same issue. I am running the Domoticz stable. I was running the Machinon theme OK, but i got an update Machinon theme (don't know exactly why because there weren't any releases). I did a git pull request and afterwards the Machinon theme didn't work anymore. Reinstalled the theme several times with no luck (and cleared the cache). What I see is that the menu layout is corrupted especially in the settings screen and the buttons are unable to edit or to view logs in it and ofcourse other stuff is not working, so the theme is not usable.

**Comment by Erwanweb** [comment]
Hi I saw this issue too. It is strange if you just come on the page, no log and other button, also Show Last Seen as Time ago do not work. IF you wait some minute on same page, all come back ok. IF you change of page or refresh, one more time it is not show well, need to wait.... Both on firefox and chrome

**Comment by Erwanweb** [comment]
Nobody find any solution on it ? MAchinon theme cannot be used anymore with domoticz 2023.2 stable, very bad...

**Comment by MadPatrick** [comment]
> Nobody find any solution on it ? MAchinon theme cannot be used anymore with domoticz 2023.2 stable, very bad...

No issue with the latest update of Machinon and Stabel 2023.2
Did you did a git update ?
