### ISSUE TITLE
Will not show all components in browser

### ISSUE THREAD

**Issue by Rouzax** [domoticz/Machinon#45]
In the mobile layout on the latest Domoticz Beta and the latest Machinon it won't show the hamburger menu.
![image](https://user-images.githubusercontent.com/4103090/92122834-3da53480-edfc-11ea-8148-bdcb3403c52e.png)

Not sure how I can help with logs?

EDIT:
It is not only the hamburger menu, there are other components missing as well.

**Comment by DewGew** [comment]
Looks like cache issue, try to clear cache

**Comment by Rouzax** [comment]
Also tried it in private mode which should bypass cache.

**Comment by Rouzax** [comment]
I can give you my URL so you can see for yourself, just send me a mail on my Github address.
Don't like posting the URL public

**Comment by Rouzax** [comment]
I've tried with different browsers to no avail
Switched different theme and removed the machinon directory from filesystem, then installed from git again and switched back, still no luck.
Wiped browser cache, but still same issue.

When I switch to a different theme everything keeps showing.

What do you need from me to be able to troubleshoot this?

**Comment by ocrghb** [comment]
same issue, no RP:
![image](https://user-images.githubusercontent.com/67554812/93572697-7f0a1800-f996-11ea-929d-69f340f46b9e.png)

**Comment by Rouzax** [comment]
Still have this issue on and off.
What do you need for me to troubleshoot?

**Comment by DewGew** [comment]
In your browsers log console is there any errors?

**Comment by ocrghb** [comment]
I think this is where the problem is coming from:
![image](https://user-images.githubusercontent.com/67554812/94992356-c5ac6480-0589-11eb-9812-98b8a0c3b817.png)

It would explain why after login and refreshing, the theme is loading fine.

**Comment by Rouzax** [comment]
This is the browser log console output of a page that will not load
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. domoticz.aaa.bbb
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery-3.5.1.min.js:2:81766
Uncaught TypeError: generate_noty is not a function
    NotifyCacheRefresh https://domoticz.aaa.bbb/#/Devices/114/Log:128
    <anonymous> https://domoticz.aaa.bbb/#/Devices/114/Log:328
domoticz.aaa.bbb:128:14
Machinon - theme settings was already found in the browser. domoticz.aaa.bbb:258:21
Machinon - found theme feature settings in Domoticz database (user variable Idx: 6) domoticz.aaa.bbb:322:33
Machinon - found theme custom settings in Domoticz database (user variable Idx: 7) domoticz.aaa.bbb:328:33
Machinon - found theme colors settings in Domoticz database (user variable Idx: 8) domoticz.aaa.bbb:334:33
The Notification permission may only be requested from inside a short running user-generated event handler. domoticz.aaa.bbb
$tooltip is now deprecated. Use $uibTooltip instead. angular.js:15635:15
Uncaught TypeError: generate_noty is not a function
    <anonymous> https://domoticz.aaa.bbb/#/Devices/114/Log:370
domoticz.aaa.bbb:370:17

```

**Comment by ocrghb** [comment]
Do you guys see what I wrote?

**Comment by StRess691** [comment]
I have a similar problem I think, I can not resolve it. I used Machinon theme from this git repository: https://github.com/EdddieN/machinon-domoticz_theme.git

I tried switching to new git, for newer version, but as soon as I installed it, I have similar screen as shown above. Both on mobile and PC.

What I made:
- originally installed theme from first git in ~/domoticz/www/styles/machinon
- installed theme from new git to ~/domoticz/www/styles/machinon_2
- cleared browser cache and tried to open domoticz in inclognito mode - without success - still elements of the GUI are missing
- removed original theme
- removed new theme
- installed new theme in ~/domoticz/www/styles/machinon
- cleared browser cache
- searched for the domoticz.js.gz file, but there is now in directory ~/domoticz/www/js, only domoticz.js is present
- I can not go to Setup / Parameters / Theme and reset the theme, because when it is enabled, there is still standard domoticz no machinon menu and theme tab is missing.
- tried to use Theme Manager plugin, but also without success.

Unfortunately all the above without any success - I still have broken GUI. I still can install old theme and it work fine for me. How can I debug it?

**Comment by StRess691** [comment]
When I investigate with use of Chrome tools, I get with the new theme this errors:
![image](https://user-images.githubusercontent.com/63842522/99881141-249c6a80-2c18-11eb-8d2c-e5d8172c7f21.png)

**Comment by ocrghb** [comment]
nobody seems to care about this serious issue. the solution is to take the latest working release : v1.15.5

**Comment by DewGew** [comment]
Im working ob this. Problem is some domoticz version works and some do work

**Comment by DewGew** [comment]
**If you are using Domoticz stable use Machinon msater. If you are using Domoticz Beta use Machinon beta!!!**
This is because moment.js is added to Domoticz in Beta

#56

**Comment by ocrghb** [comment]
I am using domoticz stable and machinon latest master. Still not working. Only 1.15.5 is OK.

**Comment by DarkAllMan** [comment]
I confirm this
