### ISSUE TITLE
Update to 1.17.1 domoticz notification

### ISSUE THREAD

**Issue by Anjerlaan** [domoticz/Machinon#66]
Hi,

I get a update to 1.17.1 notification in domoticz but on GitHub the last release is 1.16.2?
Is this correct?

**Comment by BreizhCat** [comment]
Hello

Same issue there! Each time I open Dz I have this notification:
![image](https://user-images.githubusercontent.com/16102040/101276800-ce9afb80-37af-11eb-890a-f8842e5ac705.png)

I have check the repo  but I'm already in this version:
![image](https://user-images.githubusercontent.com/16102040/101276882-5bde5000-37b0-11eb-9c3b-653d9e942355.png)

But obviously it miss something because in the conf:
![image](https://user-images.githubusercontent.com/16102040/101276888-6c8ec600-37b0-11eb-88c7-40bd2ae1c02b.png)


I'm using:
Version: 2020.2 (build 12213)
Build Hash: be4889e5d-modified
Compile Date: 2020-07-08 21:31:18
dzVents Version: 3.0.11
Python Version: 3.5.1 (default, Jan 29 2018, 14:18:59) [GCC 4.9.3 20150311 (prerelease)]

**Comment by Anjerlaan** [comment]
Do you also have error: browser cache failed notification on iPad with this 1.17.1 theme?
When I switched to default theme, the error was gone

**Comment by BreizhCat** [comment]
No I'm only using Dz on PC (Win10 + Chrome)

**Comment by DewGew** [comment]
> No I'm only using Dz on PC (Win10 + Chrome)

Clear your cache/history

**Comment by BreizhCat** [comment]
Shame on me! 
Normally I do it after a pull request and obviously I forgot this time!

Sorry for the inconvenience.

Have a good day

**Comment by Plantje1978** [comment]
I have the same issue. Using Domoticz on Windows 10 as well. Even after clearing the cache I get this notification.

**Comment by sergey08** [comment]
Same situation here.

Now with version 1.17.3

Any solution?

**Comment by DewGew** [comment]
Clear your cache/history or hit F12 right click on refresh button then choose "Empty cache and hard refresh"
